name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        stack-version: '2.15.5'
        cabal-version: '3.10.3.0'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt install gcc libgmp-dev libffi-dev libbsd-dev libc6-dev libncurses5-dev libc6 libffi8 libgmp10 libtinfo6 tar

    - name: Install dependencies
      run: |
        stack update
        stack install agda2hs
        mkdir /home/runner/.agda
        cd /home/runner/.agda
        wget https://github.com/agda/agda2hs/archive/refs/tags/v1.2.tar.gz
        tar -xzvf v1.2.tar.gz
        wget -O agda-stdlib.tar https://github.com/agda/agda-stdlib/archive/v2.0.tar.gz
        tar -xzvf agda-stdlib.tar
        echo "standard-library" > defaults
        echo "/home/runner/.agda/agda-stdlib-2.0/standard-library.agda-lib" > libraries
        echo "/home/runner/.agda/agda2hs-1.2/agda2hs.agda-lib" >> libraries

    - name: Build
      run: ./build.sh

    - name: Run tests
      run: stack test
